excercise/secret_blogs/authen/urls.py
from django.urls import path

from authen.views import LoginView, LogoutView


urlpatterns = [
    path('', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout")
]

excercise/secret_blogs/blogs/urls.py
from django.urls import path

from blogs.views import BlogListView, BlogDetailView, BlogCreateView, BlogEditView, BlogDeleteView

urlpatterns = [
    path("", BlogListView.as_view(), name="blog-list"),
    path("<int:pk>", BlogDetailView.as_view(), name="blog-detail"),
    path("create", BlogCreateView.as_view(), name="blog-create"),
    path("edit/<int:pk>", BlogEditView.as_view(), name="blog-edit"),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name="blog-delete")
]

excercise/secret_blogs/category/urls.py
from django.urls import path

from category.views import CategoryListView, CategoryCreateView, CategoryEditView, CategoryDeleteView


urlpatterns = [
    path('', CategoryListView.as_view(), name="category-list"),
    path('create', CategoryCreateView.as_view(), name="category-create"),
    path('edit/<int:pk>', CategoryEditView.as_view(), name="category-edit"),
    path('delete/<int:pk>', CategoryDeleteView.as_view(), name="category-delete")
]

excercise/secret_blogs/secret_blogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authen/', include('authen.urls')),
    path('blog/', include('blogs.urls')),
    path('category/', include('category.urls'))
]

excercise/secret_blogs/authen/models.py
from django.db import models

# Create your models here.

excercise/secret_blogs/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from category.models import Category

class Blog(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)
    
    def __str__(self):
        return "{title} by {username}".format(title=self.title, username=self.author.username)
    
    def get_str_categorise(self):
        cate_list = self.categories.values_list("name", flat=True)
        joined_string_comma = ', '.join([item for item in cate_list])
        return joined_string_comma
        

excercise/secret_blogs/category/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=10, default="#FFFFFF")
    
    def __str__(self) -> str:
        return self.name

excercise/secret_blogs/blogs/forms.py
from django import forms
from .models import Blog
from django.contrib.auth.models import User
from category.models import Category


class BlogForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(
    ),  widget=forms.CheckboxSelectMultiple, required=False)

    class Meta:
        model = Blog
        fields = ['title', 'content', 'categories']

excercise/secret_blogs/category/forms.py
from django.forms import ModelForm
from category.models import Category


class CategoryModelForm(ModelForm):
    
    class Meta:
        model = Category
        fields = [
            "name",
            "color"
        ]
    

excercise/secret_blogs/authen/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from django.contrib import messages
from django.views import View


class LoginView(View):
    
    def get(self, request):
        # code here
        return render(request, 'login.html', {"form": None})
    
    def post(self, request):
        # code here
        pass


class LogoutView(View):
    
    def get(self, request):
        # code here
        pass

excercise/secret_blogs/blogs/views.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from blogs.forms import BlogForm
from django.core.exceptions import PermissionDenied
from django import views
from blogs.models import Blog


def is_my_blog(user, author):
    if user == author:
        return True
    return False


class BlogListView(views.View):
    
    def get(self, request: HttpRequest):
        blog_qs = Blog.objects.all()
        context = {
            "blogs": blog_qs
        }
        return render(request, 'blog_list.html', context)


class BlogDetailView(views.View):
    
    def get(self, request: HttpRequest, pk):
        blog = get_object_or_404(Blog, pk=pk)
        form = BlogForm(instance=blog)
        context = {
            "blog": blog,
            "form": form
        }
        return render(request, "blog_detail.html", context)
    

class BlogCreateView(views.View):
    
    def get(self, request: HttpRequest):
        form = BlogForm()
        context = {
            "form": form
        }
        return render(request, 'blog_create.html', context)
    
    def post(self, request: HttpRequest):
        form = BlogForm(request.POST)
        
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog.save()
            form.save_m2m()
            return redirect('blog-list')
        else:
            return render(request, "blog_create.html", {"form": form})
            

class BlogEditView(views.View):
    
    def post(self, request: HttpRequest, pk):
        blog = get_object_or_404(Blog, pk=pk)
        
        if not is_my_blog(request.user, blog.author):
            raise PermissionDenied("Only for the blog owner.")
        
        form = BlogForm(request.POST, instance=blog)
        
        if form.is_valid():
            form.save()
            return redirect('blog-detail', pk=blog.id)
        else:
            context = {
                "blog": blog,
                "form": form  
            }
            return render(request, "blog_detail.html", context)
        
        
class BlogDeleteView(views.View):
    
    def get(self, request: HttpRequest, pk):
        blog = get_object_or_404(Blog, pk=pk)
        
        if not is_my_blog(request.user, blog.author):
            if not request.user.is_staff:
                raise PermissionDenied("Only for the blog owner.")

        blog.delete()
        return redirect('blog-list')
        

excercise/secret_blogs/category/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib import messages
from category.models import Category
from category.forms import CategoryModelForm


class CategoryListView(View):
    
    def get(self, request: HttpRequest):
        category_qs = Category.objects.all()
        
        form_category_list = [
            CategoryModelForm(instance=category)
            for category in category_qs
        ]
        context = {
            "forms": form_category_list,
            "category_qs": category_qs
        }
        
        return render(request, "list_category.html", context)
    

class CategoryCreateView(View):
    
    def post(self, request: HttpRequest):
        form = CategoryModelForm(request.POST)
        
        if form.is_valid():
            form.save()
        else:
            non_field_errors_mes = str(form.non_field_errors())
            messages.error(request, "create error {error}".format( error=non_field_errors_mes ))
            
        return redirect('category-list')
        

class CategoryEditView(View):
    
    def post(self, request: HttpRequest, pk):
        category = get_object_or_404(Category, pk=pk)
        form = CategoryModelForm(request.POST, instance=category)
        
        if form.is_valid():
            form.save()
            
        return redirect('category-list')


class CategoryDeleteView(View):
    
    def get(self, request: HttpRequest, pk):
        category = get_object_or_404(Category, pk=pk)
        category.delete()
        return redirect('category-list')
        

excercise/secret_blogs/authen/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <h2 class="text-center">Login</h2>
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            {{ form.username.errors }}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            {{ form.password.errors }}
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary w-100">Login</button>
            <br>
            <br>
            {% if messages %}
                <div>
                    {% for message in messages %}
                        <p class="text-danger">{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

excercise/secret_blogs/blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Title{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary p-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog-list' %}" style="color: rgb(245, 244, 243);">
                Secret Blog by .....
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto ">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <p class="nav-link text-light"> I'm, {{ user.username }}</p>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" href="{% url 'logout' %}"><b>Logout</b></a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container py-4">
            <!-- Navbar -->

        {% block content %}
            <div class=""></div>
        {% endblock %}
    </div>
</body>
</html>

excercise/secret_blogs/blogs/templates/blog_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h1 class="mb-4">Create New Blog Post</h1>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_title" class="form-label">Title</label>
                    <br>
                    {{ form.title }}
                    {{ form.title.errors }}
                </div>
                <div class="mb-3">
                    <label for="id_content" class="form-label">Content</label>
                    <br>
                    {{ form.content }}
                    {{ form.content.errors }}
                </div>
                <div class="mb-3">
                    <label for="id_content" class="form-label">Categories</label>
                    <br>
                    {{ form.categories }}
                    {{ form.categories.errors }}
                </div>
                <button type="submit" class="btn btn-success">Create Blog</button>
                <a href="{% url 'blog-list' %}" class="btn btn-secondary">Back to Blog List</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

excercise/secret_blogs/blogs/templates/blog_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
             <!-- Blog content (initially visible) -->
            <div id="view-mode">
                <div class="d-flex justify-content-between">
                    <h1 class="mb-4">{{ blog.title }}</h1>
                    <!-- 
                        ซ่อนปุ่ม สร้าง blog และปุ่มสร้าง category ให้แสดงเฉพาะ role ที่มีสิทธิ์เท่านั้น 
                        และให้่แสดงเฉพาะ ปุ่มแก้ไข/ลบ เฉพาะ user ที่เป็นเข้าของ blog เท่านั้น
                        และแสดงปุ่มลบเฉพาะ user ที่มีสิิทธิ์ Admin

                       ** Hitt: user.is_staff, user == author
                    -->
                        <div class="btn-group">
                            <button class="btn sm btn-warning m-2" id="edit-btn">Edit</button>
                        
                            <button class="btn sm btn-danger m-2">
                                <a href="{% url 'blog-delete' blog.id %}" style="text-decoration: none; color:antiquewhite">Delete</a>
                            </button>

                        </div>
                  
                </div>
                
                <div class="create-box">
                    <p class="text-muted">
                        By {{ blog.author.username }} on {{ blog.created_at|date:"Y-m-d H:i" }}
                    </p>
                    <p>Catagories: </p>
                    <div class="d-flex align-items-center">
                        {% for category in blog.categories.all %}
                        <div style="background-color: {{category.color}} !important;" class="p-1 mx-1">
                            {{category.name}}
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <hr>
                <div class="content">
                    {{ blog.content|safe }}
                </div>
                <hr>
                <a href="{% url 'blog-list' %}" class="btn btn-primary mt-3">Back to Blog List</a>
            </div>
            
            <!-- Edit Mode -->
            <div id="edit-mode" style="display: none;">
                <form action="{% url 'blog-edit' blog.id %}" method="post">
                    {% csrf_token %}
                    <label class=""><h1>Title</h1></label>
                    <div class="title py-1 pb-2">
                        {{ form.title }}
                        {{ form.title.errors }}
                    </div>
                    {{ form.content.label }}
                    <div class="conent py-1">
                        {{ form.content }}
                        {{ form.content.errors }}
                    </div>

                    {{ form.categories.label }}
                    <div class="categories py-1">
                        {{ form.categories }}
                        {{ form.categories.errors }}
                    </div>
                    <button type="submit" class="btn btn-success">Save Changes</button>
                    <button type="button" class="btn btn-secondary" id="cancel-btn">Cancel</button>
                    
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('edit-btn').addEventListener('click', function() {
        document.getElementById('view-mode').style.display = 'none';
        document.getElementById('edit-mode').style.display = 'block';
    });

    document.getElementById('cancel-btn').addEventListener('click', function() {
        document.getElementById('edit-mode').style.display = 'none';
        document.getElementById('view-mode').style.display = 'block';
    });
</script>

{% endblock %}

excercise/secret_blogs/blogs/templates/blog_list.html
{% extends 'base.html' %}

{% block title %} Blogs List {% endblock %}
{% block content %}
<h1 class="mb-4">Blog List</h1>
<div class="row pb-2">
    <!-- ซ่อนปุ่ม สร้าง blog และปุ่มสร้าง category ให้แสดงเฉพาะ role ที่มีสิทธิ์เท่านั้น -->

    <div class="col">
        <!-- btn for create blog -->
        <a type="button" class="btn btn-primary" href="{% url 'blog-create' %}">Create</a>
    </div>

    <div class="col">
        <!-- btn for manage category -->
        <a type="button" class=" btn btn-info text-white" href="{% url 'category-list' %}" >Blog Category</a>
    </div>
    
</div>
<div class="row">
    <div class="col-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Categories</th>
                    <th scope="col">Created At</th>
                </tr>
            </thead>
            <tbody>
                {% for blog in blogs %}
                <tr>
                    <td><a href="{% url 'blog-detail' blog.id %}">{{blog.title }}</a></td>
                    <td>{{ blog.author.username }}</td>
                    <td>{{blog.get_str_categorise}}</td>
                    <td>{{ blog.created_at|date:"Y-m-d H:i" }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3" class="text-center">No blog posts available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

excercise/secret_blogs/category/templates/create_dialog.html
<div class="p-2">
    <!-- <button type="button" class="btn btn-sm btn-success p-1">Create Category</button> -->
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">New Category</a>
    <div class="row">
        <div class="col">
          <div class="collapse multi-collapse" id="multiCollapseExample1">
            <div class="card card-body">
                <form action="{% url 'category-create' %}" method="post">
                    {% csrf_token %}
                    <div class="category-form">
                        <div class="name-input py-2">
                            <label for="name-input">Name</label>
                            <input class="form-control" type="text" name="name" placeholder="category name">
                        </div>

                        <div class="color-input">
                            <label for="color-input">Color</label>
                            <input type="color" class="form-control form-control-color" name="color" value="#FFF0FF">
                        </div>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-success py-2">Save</button>
                </form>
            </div>
          </div>
     </div>
</div>

excercise/secret_blogs/category/templates/list_category.html
{% extends 'base.html' %}

{% block title %} Category List {% endblock %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="d-flex">
                <h1 class="mb-4">Category List</h1>
                {% include 'create_dialog.html' %}
            </div>
        </div>
    </div>
    <br>
    
    {% for form in forms %}
    <div class="row py-1">
        <div class="col">
            <div class="border border-dark p-3 ">
                <!-- View Model -->
                <div id="view-mode-{{form.instance.id}}" >
                    <div class="d-flex justify-content-between">
                        <div class="">
                            <p>Name: </p>
                            <h5>{{form.instance.name}}</h5>
                        </div>
                        <div class="">
                            <p for="">Color: </p>
                            <input type="color" class="form-control form-control-color" id="favcolor" name="favcolor" value="{{form.instance.color}}" disabled>
                        </div>
                        <div class="">
                            <button type="button" class="btn btn-warning" id="edit-btn-{{form.instance.id}}">Edit</button>
                            <a href="{% url 'category-delete' form.instance.id %}" type="button" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>

                <!-- Edit Mode -->
                <div id="edit-mode-{{form.instance.id}}"  style="display: none !important;">
                    <form action="{% url 'category-edit' form.instance.id %}" method="post">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <div class="name">
                                <p>Name: </p>
                                <h5>{{form.name}}</h5>
                            </div>
                            <div class="input-color">
                                <p for="color">Color: </p>
                                <input type="color" class="form-control form-control-color" name="color" value="{{form.instance.color}}">
                            </div>

                            {% if form.form.non_field_errors%}
                            <div class="error_fields">
                                {{ form.form.non_field_errors }}
                            </div>
                            {% endif %}

                            <div class="btns-group">
                                <button type="submit" class="btn btn-success">Save</button>
                                <button type="button" class="btn btn-secondary" id="cancel-btn-{{form.instance.id}}">Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% for form in forms %}
<script>
    document.getElementById('edit-btn-{{form.instance.id}}').addEventListener('click', function() {
        document.getElementById('view-mode-{{form.instance.id}}').style.display = 'none';
        document.getElementById('edit-mode-{{form.instance.id}}').style.display = 'block';
    });

    document.getElementById('cancel-btn-{{form.instance.id}}').addEventListener('click', function() {
        document.getElementById('edit-mode-{{form.instance.id}}').style.display = 'none';
        document.getElementById('view-mode-{{form.instance.id}}').style.display = 'block';
    });
</script>
{% endfor %}

{% endblock %}